    name: Build Kivy APK

    on:
      push:
        branches:
          - main # Or your desired branch

    jobs:
      build:
        runs-on: ubuntu-latest # Buildozer requires a Linux environment

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10-slim' # Specify your Python version

        - name: Install Buildozer dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential ccache git libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386

        - name: Install Buildozer
          run: pip install buildozer

        - name: Build Android APK
          run: buildozer android debug

        - name: Upload APK artifact
          uses: actions/upload-artifact@v4
          with:
            name: kivy-apk
            path: bin/*.apk # Adjust path if your APK is in a different location
